name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - uses: montudor/action-zip@v1
      - name: Zip the directory
        run: zip -r test.zip .
      - name: Upload test.zip
        uses: actions/upload-artifact@v3
        with:
          name: test.zip
          path: test.zip

      - name: Run Maven packages without tests
        run: mvn --batch-mode clean package --file pom.xml -DskipTests

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Run Maven with tests
        run: mvn -B test --file pom.xml

  Veracode_SCA_Scan:
    runs-on: ubuntu-latest
    needs: test
    name: "Veracode SCA Scan"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: "${{ secrets.SRCCLR_API_TOKEN }}"
        uses: veracode/veracode-sca@v2.1.9

  Veracode_SAST_Scan:
    runs-on: ubuntu-latest
    needs: test
    name: "Veracode SAST Scan"
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: test.zip

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.8
        with:
          vid: "${{ secrets.VERACODE_API_KEY_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY_SECRET }}"
          app_id: "david-cicd-test"
          file: "test.zip"

  import-issues:
    needs: Veracode_SAST_Scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get scan results
        uses: actions/download-artifact@v3
        with:
          name: 'Veracode Pipeline-Scan Results'

      - name: import flaws as issues
        uses: veracode/veracode-flaws-to-issues@v2.1.19
        with:
          scan-results-json: 'filtered_results.json'
          github-token: ${{ secrets.PRIVATE_TOKEN }}

      - uses: montudor/action-zip@v1
      - name: Zip the directory
        run: zip -r test.zip .

      - name: Veracode Sandbox Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: "david-cicd-test"
          scantimeout: 30
          scanpollinginterval: 30
          createsandbox: "true"
          sandboxname: "TestGitHub"
          filepath: "filtered_results.json"
          vid: "${{ secrets.VERACODE_API_KEY_ID }}"
          vkey: "${{ secrets.VERACODE_API_KEY_SECRET }}"
          criticality: 'High'
          deleteincompletescan: 1
          debug: "true"
